title: My Site
description: Simple test
# Adjust these two correctly (see #3 above)
url: "https:/tellusant.github.io"
baseurl: "/docs"   # for user/org site; use "/repo" for project site

plugins:
  - jekyll-seo-tag    # both are GitHub Pages–approved
  - jekyll-feed
