# ------------------------------------------------------------
# Site
# ------------------------------------------------------------

title: "Tellusant Publications Repository"
description: "This open access repository contains the complete published works by Tellusant team members. They range from scientific papers, to TV and radio appearances, to social media posts, and much more."

url: "https://docs.tellusant.com"
baseurl: ""

image: "/assets/social-card-publ.png"
logo: "/assets/images/tellusant-logo.png"


# ------------------------------------------------------------
# Tellusant organization
# ------------------------------------------------------------

company:
  name: "Tellusant, Inc."
  url: "https://tellusant.com/"
  same_as:
    - "https://www.linkedin.com/company/tellusant/"
    - "https://vimeo.com/tellusant"
    - "https://www.threads.com/@tellusant"


# ------------------------------------------------------------
# Used by jekyll-seo-tag
# ------------------------------------------------------------

social:
  name: "Tellusant, Inc."
  links:
    - "https://www.linkedin.com/company/tellusant/"
    - "https://vimeo.com/tellusant"
    - "https://www.threads.com/@tellusant"


# ------------------------------------------------------------
# Related sites
# ------------------------------------------------------------

related_sites:
  company:
    name: "Tellusant"
    url: "https://tellusant.com/"

  tellubase:
    name: "TelluBase"
    url: "https://tellubase.com/"


# ------------------------------------------------------------
# Jekyll plugins
# ------------------------------------------------------------

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from      
