title: "TELLUSANT, INC."
description: "This website contains published materials by Tellusant team members."
url: "https://tellusant.github.io"   # no trailing slash
# If your site lives at /docs on that host (project page):
baseurl: "/docs"                     # omit if site is at the root
plugins:
  - jekyll-sitemap
- jekyll-seo-tag

collections:
  publications:
    output: true

just_the_docs:
  collections:
    publications:
      name: "Tellusant Publications"

---
title: Overview
nav_order: 1
has_children: true
parent: Tellusant Publications
permalink: /docs/

---
title: README
nav_order: 2
parent: Tellusant Publications
permalink: /docs/overview/
---

---
title: Some Paper
nav_order: 10
parent: Tellusant Publications
---
