theme: minima  # or your theme/remote_theme
site_name: "TELLUSANT, INC."
description: "Publications by Tellusant team members"

url: "https://tellusant.github.io"
baseurl: "/docs"
plugins:
#  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  
include:
  - assets/css/main.scss
  - sitemap.xml


# SC test
# defaults:
#   - scope:
#       path: ""
#     values:
#       image: https://tellusant.github.io/docs/assets/social-card.png
      
