## remote_theme: just-the-docs/just-the-docs
title: "Tellusant Publications NW"
description: "Published materials by Tellusant team members NW"
search_enabled: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
