title: "TELLUSANT, INC."
description: "Published materials by Tellusant team members"

url: "https://tellusant.github.io"
baseurl: "/docs"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
# SC test
# defaults:
#   - scope:
#       path: ""
#     values:
#       image: https://tellusant.github.io/docs/assets/social-card.png
      
