
name: IndexNow Submit

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual triggering

jobs:
  submit-indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Submit URLs to IndexNow
        run: |
          echo "https://yourdomain.github.io/page1" > urls.txt
          echo "https://yourdomain.github.io/page2" >> urls.txt

          while read url; do
            echo "Submitting $url"
            curl -s -o /dev/null -w "%{http_code}\n" "https://www.bing.com/indexnow?url=$url&key=${{ secrets.INDEXNOW_KEY }}"
          done < urls.txt
